apiVersion: ako.vmware.com/v1alpha1
kind: AviInfraSetting
metadata:
  name: dmz-infra-setting
spec:
  seGroup:
    name: Default-Group #Make sure this matches your Service Engine Group that you've configured in Avi!
  network:
    vipNetworks:
      - networkName: "Example Network" #Add your Network Name here
        cidr: 10.10.60.0/24 #Add your CIDR here
    enableRhi: false
  l7Settings:
    shardSize: MEDIUM
