# Example Cluster with small sized worker nodes, best effort
# It includes an example of how you can have the storage policy (and thus, location) be different for the TKC nodes, 
# versus where or how you want the Persistant Volumes for pods to be stored. 
# For more information, see: https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-2597788E-2FA4-420E-B9BA-9423F8F7FD9F.html
apiVersion: run.tanzu.vmware.com/v1alpha1      #TKGS API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: tkgs-example-cluster-small             #cluster name, user defined
  namespace:  Namespace01                      #vsphere namespace
spec:
  distribution:
    version: 1.19                              #Resolves to the latest v1.19 image
  topology:
    controlPlane:
      count: 3                                 #number of control plane nodes
      class: best-effort-small                 #vmclass for control plane nodes
      storageClass: tanzu                      #storageclass for control plane
    workers:
      count: 3                                 #number of worker nodes
      class: best-effort-small                 #vmclass for worker nodes
      storageClass: tanzu                      #Example Storageclass, should be available in the NameSpace that this cluster is made inside of
  settings:
    storage:
      defaultClass: tanzu-pvc  # Example storageclass for container persistant storage only (PVC = Persistant volume claims). Should be available in the NameSpace that this cluster is made inside of