---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spaceinvaders
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spaceinvaders
  replicas: 1 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: spaceinvaders
    spec:
      containers:
      - name: spaceinvaders
        image: vpotusflotus/demos:spaceinvadershtml5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spaceinvaders-lb
  namespace: default
  labels:
    app: spaceinvaders-lb
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: spaceinvaders
  type: LoadBalancer
