# Example Cluster with small sized worker nodes, best effort
# It includes an example of how you can have the storage policy (and thus, location) be different for the TKC nodes, 
# versus where or how you want the Persistant Volumes for pods to be stored. 
# For more information, see: https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-2597788E-2FA4-420E-B9BA-9423F8F7FD9F.html
apiVersion: run.tanzu.vmware.com/v1alpha2 #TKGS API endpoint
kind: TanzuKubernetesCluster #required parameter
metadata:
  name: tkgs-fluffcluster2-ns1-cluster1 #cluster name, user defined
  namespace: ns1-workload1 #vsphere namespace
spec:
  topology:
    controlPlane:
      replicas: 1 #amount of master nodes
      vmClass: best-effort-small #The VM size to use for the master nodes
      storageClass: vsan-default-storage-policy #The storageclass as defined and available in the namespace
      tkr:  #Tanzu Kubernetes Release
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55 #Which Tanzu Kubernetes Release should be used, currently these must match between master and worker nodes
    nodePools:
    - name: worker-nodepool-a1
      replicas: 2 #amount of worker nodes
      vmClass: best-effort-small #The VM size to use for the worker nodes
      storageClass: vsan-default-storage-policy #The storageclass as defined and available in the namespace
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55 #Which Tanzu Kubernetes Release should be used, currently these must match between master and worker nodes